// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

// Keys are written without the tool prefix here and get "interest-calculator." added below.
const en = {
  name: 'interest calculator',
  modes: 'Situation',
  'mode.loan': 'Loan',
  'mode.savings': 'Savings',
  'mode.payoff': 'Pay off debt',
  'mode.rate': 'Find the rate',
  'intro.loan': 'Monthly payment and total cost of a loan with a fixed rate, such as a mortgage, car loan or student loan.',
  'intro.savings': 'How savings or investments grow with interest and regular deposits.',
  'intro.payoff': 'How long a debt takes to clear at a fixed monthly payment, such as a credit card balance.',
  'intro.rate': 'The real yearly cost of a loan offer, worked out from the amount, the payment and the fees.',

  // Fields
  'f.loan.amount': 'Amount borrowed',
  'f.loan.rate': 'Interest rate',
  'f.loan.term': 'Repayment time',
  'f.loan.kind': 'Repayment type',
  'f.loan.extra': 'Extra payment each month',
  'h.loan.kind': 'Equal payments: the same amount every month. Equal principal: the loan falls by the same amount every month, so payments start higher and fall.',
  'h.loan.extra': 'Optional. Paid on top of every payment, straight off the loan.',
  'o.annuity': 'Equal payments',
  'o.serial': 'Equal principal',
  'f.savings.start': 'Starting amount',
  'f.savings.monthly': 'Deposit each month',
  'f.savings.rate': 'Interest or return',
  'f.savings.term': 'Time',
  'f.savings.compounding': 'Interest added',
  'f.savings.inflation': 'Inflation',
  'h.savings.compounding': 'How often interest is added to the balance and starts earning interest itself.',
  'h.savings.inflation': 'Optional. Shows what the end amount is worth in today’s money.',
  'o.monthly': 'Monthly',
  'o.daily': 'Daily',
  'o.yearly': 'Yearly',
  'o.simple': 'Never (simple interest)',
  'f.payoff.balance': 'Amount owed',
  'f.payoff.rate': 'Interest rate',
  'f.payoff.payment': 'Payment each month',
  'f.rate.amount': 'Amount borrowed',
  'f.rate.payment': 'Payment each month',
  'f.rate.term': 'Repayment time',
  'f.rate.upfrontFee': 'Fees at the start',
  'f.rate.monthlyFee': 'Fee each month',
  'h.rate.payment': 'Without any monthly fee.',
  'h.rate.upfrontFee': 'Optional. Setup or arrangement fees, taken off what you receive.',
  'h.rate.monthlyFee': 'Optional. A fixed fee added to every payment.',
  'u.pct': '% a year',
  'u.month': 'a month',
  'u.unit': 'Unit',
  'u.years': 'years',
  'u.months': 'months',

  // Field errors
  'err.number': 'Enter a number, like 250000 or 4.5',
  'err.positive': 'Enter an amount above 0',
  'err.nonneg': 'Enter 0 or more',
  'err.rate': 'Enter a rate from 0 to 100',
  'err.term': 'Enter a time from 1 month to 100 years',
  'invalid': 'Fix the marked fields to see the result.',

  // Shared result parts
  result: 'Result',
  about: 'about {words}',
  perspective: 'In perspective',
  perOne: 'You pay back {x} for every 1 you borrow.',
  legend: '{label}: {value}, {pct}',
  total: 'Total {value}',
  year: 'Year',
  byYear: 'Year by year',
  method: 'How this is calculated',
  disclaimer: 'Estimates for comparing options, not financial advice. Real lenders and banks may round payments, add fees or change the rate.',
  principal: 'Principal',
  interest: 'Interest',
  balance: 'Balance at year end',
  'chart.paid': 'Paid each year',
  'chart.paidLabel': 'Bar chart of what is paid each year, split into principal and interest, over {n} years. Interest is {first} of year 1 and {last} of the last year.',
  'dur.y.one': '{n} year',
  'dur.y.other': '{n} years',
  'dur.m.one': '{n} month',
  'dur.m.other': '{n} months',
  'dur.both': '{y} {m}',

  // Loan
  'loan.payment': 'Monthly payment',
  'loan.over': '{n} payments over {time}',
  'loan.firstPayment': 'First monthly payment',
  'loan.falling': 'falling to {last} by the last payment',
  'loan.totalInterest': 'Total interest',
  'loan.totalPaid': 'Total paid',
  'loan.time': 'Paid off in',
  'loan.borrowed': 'Borrowed',
  'loan.share': 'About {time} of the {total} of payments go to interest alone.',
  'loan.day': 'Right now interest costs about {day} a day, {month} in the first month.',
  'loan.split': 'Interest is {first} of the first payment and {last} of the last.',
  'loan.extra': 'Paying {extra} extra a month clears the loan {sooner} sooner and saves {saved} in interest.',
  'loan.rates': 'If the rate changes',
  'loan.rates.rate': 'Rate',
  'loan.rates.now': '{rate} (yours)',
  'loan.rates.diff': 'Change a month',
  'loan.announce': '{label} {value}. Total interest {interest}.',
  'loan.method.annuity': 'Monthly payment = P × r ÷ (1 − (1 + r)^−n), where P is the amount borrowed, r is the yearly rate ÷ 12 and n is the number of months. Each month the interest is the balance × r, and the rest of the payment reduces the balance.',
  'loan.method.serial': 'Each month you repay P ÷ n of the loan, where P is the amount borrowed and n the number of months, plus interest of the balance × r, where r is the yearly rate ÷ 12.',
  'loan.method.extra': 'An extra payment goes straight off the balance, so the loan ends sooner.',

  // Savings
  'sav.after': 'Amount after {time}',
  'sav.deposits': 'Your deposits',
  'sav.putIn': 'You put in',
  'sav.earned': 'Interest earned',
  'sav.real': 'In today’s money',
  'sav.share': 'Interest makes up {pct} of the final amount.',
  'sav.each': 'Every 1 you put in becomes {x}.',
  'sav.double': 'At this rate, money doubles in about {years} years.',
  'sav.doubleNever': 'At 0 % the money does not grow.',
  'sav.last': 'In the last year interest adds {amount}, about {month} a month.',
  'sav.lastMore': 'In the last year interest adds {amount}, about {month} a month: more than your monthly deposit of {deposit}.',
  'sav.lastLess': 'In the last year interest adds {amount}, about {month} a month: less than your monthly deposit of {deposit}.',
  'sav.inflation': 'With {inf} inflation a year, that buys about what {real} buys today.',
  'sav.chart': 'Balance at the end of each year',
  'sav.chartLabel': 'Bar chart of the balance at the end of each year, split into deposits and interest, over {n} years. It ends at {total}, of which {interest} is interest.',
  'sav.balance': 'Balance',
  'sav.announce': '{label}: {value}. Interest earned {interest}.',
  'sav.method.compound': 'Interest of {rate} a year is added {freq}, which comes to {eff} a year. The calculation runs month by month at the equivalent monthly rate. Deposits are made at the end of each month and earn interest from the month after.',
  'sav.method.simple': 'Simple interest: every amount you put in earns {rate} a year of itself only. Interest is kept apart and never earns interest of its own.',
  'freq.daily': 'daily',
  'freq.monthly': 'monthly',
  'freq.yearly': 'yearly',

  // Pay off
  'pay.time': 'Paid off in',
  'pay.by': 'by {date}',
  'pay.owed': 'Owed',
  'pay.perOne': 'You pay back {x} for every 1 you owe.',
  'pay.first': 'Of your first payment, {interest} goes to interest and {principal} to the debt.',
  'pay.never': 'At this payment the debt is never paid off: the interest alone is {interest} a month. Pay more than that to bring it down.',
  'pay.tooLong': 'At this payment the debt takes over 100 years to pay off.',
  'pay.more': 'Paying more each month',
  'pay.more.payment': 'Payment',
  'pay.more.time': 'Paid off in',
  'pay.more.saved': 'Interest saved',
  'pay.more.now': '{value} (yours)',
  'pay.announce': 'Paid off in {time}. Total interest {interest}.',
  'pay.announceNever': 'Never paid off at this payment.',
  'pay.method': 'Each month, interest of the balance × r is added, where r is the yearly rate ÷ 12, and then your payment is taken off. The last payment is only what is left.',

  // Find the rate
  'rate.effective': 'Real cost a year',
  'rate.nominal': 'nominal rate {rate} a year',
  'rate.totalPaid': 'Total paid',
  'rate.cost': 'Cost of the loan',
  'rate.costMonth': 'Cost a month',
  'rate.borrowed': 'Borrowed',
  'rate.costPart': 'Interest and fees',
  'rate.fees': 'Without the fees the real cost would be {rate} a year, so the fees add {pp} percentage points.',
  'rate.compare': 'At {rate} a year, borrowing {base} for a year costs about {cost}.',
  'rate.none': 'The payments add up to less than the amount borrowed, so there is no interest to find.',
  'rate.announce': 'Real cost {rate} a year.',
  'rate.method': 'Finds the monthly rate r at which the amount you receive (the amount borrowed minus fees at the start) equals the value today of all your payments, fees included. The nominal rate is r × 12. The real cost a year is (1 + r)^12 − 1: it counts interest on interest and all fees, so it is the figure to compare offers by.',
};

export const strings = {
  en: Object.fromEntries(Object.entries(en).map(([k, v]) => [`interest-calculator.${k}`, v])),
};
