// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

const P = 'pick-a-person';

export const strings = {
  en: Object.fromEntries(Object.entries({
    name: 'pick a person',
    mode: 'Mode',
    'mode.bottle': 'bottle',
    'mode.fingers': 'fingers',
    'mode.wheel': 'wheel',
    'mode.straws': 'straws',
    'mode.teams': 'teams',
    options: 'Options',
    skip: 'Show result',
    player: 'player {n}',

    players: 'players',
    'source.count': 'number',
    'source.names': 'names',
    count: 'Players',
    fewer: 'One fewer player',
    more: 'One more player',
    countSaid: '{n} players',
    addLabel: 'Add names, one at a time or separated by commas',
    add: 'Add',
    list: 'Names',
    remove: 'Remove {name}',
    clear: 'Remove all names',
    added: 'Added {name}',
    addedMany: 'Added {n} names',
    removed: 'Removed {name}',
    'names.count': '{n} names. Tap a name to remove it.',
    'names.few': 'Add at least two names. Until then {count} numbered players are used.',
    'names.full': 'The list is full at {max} names.',

    settings: 'settings',
    vibrate: 'Vibrate on results',
    help: 'how it works',
    'help.bottle': 'Lay the phone flat in the middle of the group and spin the bottle. It stops pointing at someone.\nFlick the bottle with a finger, tap it, or press Spin. With names, they sit around the edge in list order: go round the table the same way.',
    'help.fingers': 'Everyone puts one finger on the screen and holds still. After a short countdown the result shows under the fingers: one person, teams or an order.\nIf a finger lifts or a new one joins, the countdown starts again. Without a touch screen, the players stand in a circle instead.',
    'help.wheel': 'One segment per player. Spin and see where the pointer stops.\nTurn on taking winners off the wheel to pick people one after another.',
    'help.straws': 'One straw per player stands in the cup. One of them is short.\nPass the phone round in list order. Each player taps a straw until someone pulls out the short one.',
    'help.teams': 'Splits the players into random teams. Team sizes differ by at most one.\nChoose how many teams, or how many players per team.',

    'bottle.spin': 'Spin',
    'bottle.again': 'Spin again',
    'bottle.spinning': 'Spinning',
    'bottle.points': 'The bottle stopped, pointing at {hour} o’clock.',
    'bottle.picked': 'is picked',

    'fingers.kind': 'Pick',
    'fingers.kind.one': 'one',
    'fingers.kind.teams': 'teams',
    'fingers.kind.order': 'order',
    'fingers.simulate': 'Pick from {n} players',
    'fingers.hint.touch': 'Everyone put a finger on the screen',
    'fingers.hint.noTouch': 'This needs a touch screen. Or pick from the players below.',
    'fingers.hint.more': 'Waiting for more fingers',
    'fingers.hint.hold': 'Hold still',
    'fingers.hint.lift': 'Lift all fingers to start again',
    'fingers.hint.again': 'Touch the screen to start again',
    'fingers.said.one': '{name} is picked.',
    'fingers.said.place': '{place}: {name}',

    'wheel.spin': 'Spin',
    'wheel.again': 'Spin again',
    'wheel.spinning': 'Spinning',
    'wheel.picked': 'is picked',
    'wheel.remove': 'Take each winner off the wheel',
    'wheel.left': '{n} of {of} left on the wheel',
    'wheel.reset': 'Put everyone back',
    'wheel.restored': 'Everyone is back on the wheel.',

    'straws.turn': '{name}, pick a straw',
    'straws.rest': 'Draw the rest',
    'straws.again': 'New draw',
    'straws.ready': '{n} straws. One is short.',
    'straws.label': 'Straw {n}',
    'straws.label.long': 'Straw {n}, drawn by {name}: long',
    'straws.label.short': 'Straw {n}, drawn by {name}: short',
    'straws.long': '{name} drew a long straw.',
    'straws.short': 'drew the short straw',

    'teams.by': 'Split by',
    'teams.by.teams': 'teams',
    'teams.by.size': 'team size',
    'teams.count': 'Number of teams',
    'teams.size': 'Players per team',
    'teams.make': 'Make teams',
    'teams.again': 'Shuffle again',
    'teams.hint': '{n} players, ready to split',
    'teams.team': 'Team {team}',
    'teams.said': 'Team {team}: {names}',
    'teams.copy': 'Copy',
    'teams.copied': 'Teams copied',
    'teams.copyFailed': 'Couldn’t copy. Select the teams and copy them instead.',
  }).map(([k, v]) => [`${P}.${k}`, v])),
};
