// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

export const strings = {
  en: {
    'sign-document.name': 'sign document',
    'sign-document.lead': 'Open a PDF or a picture of a document, add your signature, drawing or text, and save a signed copy.',
    'sign-document.open': 'Open a document',
    'sign-document.formats': 'PDF, PNG, JPEG or WebP. You can also drop a file here.',
    'sign-document.privacy': 'Files are read in this browser and never uploaded. This adds a picture of your signature; it isn’t a certified digital signature.',
    'sign-document.opening': 'Opening…',
    'sign-document.opened': 'Opened {name}',
    'sign-document.document': 'Document',
    'sign-document.meta.pdf': 'PDF, {n} pages',
    'sign-document.meta.pdf1': 'PDF, 1 page',
    'sign-document.meta.image': 'Picture',
    'sign-document.missing': 'Some parts of this PDF, such as certain images or shaded areas, can’t be shown in this preview. They’re kept unchanged in the saved file.',
    'sign-document.save': 'Save signed PDF',
    'sign-document.saveImage': 'Save signed picture',
    'sign-document.savePdf': 'Save as PDF',
    'sign-document.options': 'Options',
    'sign-document.more': 'More',
    'sign-document.saveShort': 'Save',
    'sign-document.close': 'Close document',
    'sign-document.openOther': 'Open another',
    'sign-document.saving': 'Saving…',
    'sign-document.saved': 'Saved. Check your downloads.',
    'sign-document.pages': 'Pages',
    'sign-document.field': 'Form field',
    'sign-document.meta.fields': '{n} form fields',
    'sign-document.page': 'Page {n} of {total}',
    'sign-document.loadingPage': 'Loading page…',
    'sign-document.pageFailed': 'This page couldn’t be shown. Anything you add is still saved on it.',

    'sign-document.tools': 'Tools',
    'sign-document.mode.move': 'Select',
    'sign-document.mode.pen': 'Pen',
    'sign-document.mode.text': 'Text',
    'sign-document.mode.date': 'Date',
    'sign-document.modeHint.move': 'Drag items to move them, or the corner square to resize.',
    'sign-document.modeHint.pen': 'Draw on the page. Choose Move to scroll on touch screens.',
    'sign-document.modeHint.text': 'Tap the page to add text there.',
    'sign-document.modeHint.date': 'Tap the page to add today’s date, written the way this browser’s language and region write dates.',
    'sign-document.signTool': 'Sign',
    'sign-document.undo': 'Undo',
    'sign-document.undone': 'Undone',
    'sign-document.ink': 'Ink',
    'sign-document.goTo': 'Go to page',
    'sign-document.zoom.title': 'Zoom',
    'sign-document.zoom.in': 'Zoom in',
    'sign-document.zoom.out': 'Zoom out',
    'sign-document.ink.black': 'Black',
    'sign-document.ink.blue': 'Blue',

    'sign-document.item.panel': 'Selected item',
    'sign-document.item.sig': 'Signature {n}, page {page}',
    'sign-document.item.ink': 'Drawing {n}, page {page}',
    'sign-document.item.text': 'Text {n}, page {page}: {text}',
    'sign-document.item.date': 'Date {n}, page {page}: {text}',
    'sign-document.item.tick': 'Tick {n}, page {page}',
    'sign-document.item.cross': 'Cross {n}, page {page}',
    'sign-document.mark.title': 'Marks',
    'sign-document.mark.tick': 'Tick',
    'sign-document.mark.cross': 'Cross',
    'sign-document.item.defaultText': 'Text',
    'sign-document.item.dateLabel': 'Date',
    'sign-document.item.formatLabel': 'Written as',
    'sign-document.item.textLabel': 'Text',
    'sign-document.item.smaller': 'Smaller',
    'sign-document.item.larger': 'Larger',
    'sign-document.item.delete': 'Delete',
    'sign-document.item.allPages': 'Put on every page',
    'sign-document.copied': 'Copied to the other {n} pages',
    'sign-document.copied1': 'Copied to the other page',
    'sign-document.item.keys': 'Arrow keys move the selected item, with Shift for bigger steps. Plus and minus resize it, Delete removes it.',
    'sign-document.placed': 'Signature placed on page {page}',
    'sign-document.removed': 'Removed',

    'sign-document.sig.title': 'Signatures',
    'sign-document.sig.none': 'No saved signatures yet.',
    'sign-document.sig.openFirst': 'Open a document to place a signature.',
    'sign-document.sig.tap': 'Choose a signature to place it on the page in view.',
    'sign-document.sig.new': 'New',
    'sign-document.sig.newTitle': 'new signature',
    'sign-document.sig.source': 'Make it by',
    'sign-document.sig.draw': 'Drawing',
    'sign-document.sig.type': 'Typing',
    'sign-document.sig.picture': 'Picture',
    'sign-document.sig.padLabel': 'Signature preview. Draw here with a mouse, finger or stylus when Drawing is chosen.',
    'sign-document.sig.hint.draw': 'Sign in the box above.',
    'sign-document.sig.hint.type': 'Your name is shown in a handwriting-style font, which depends on your device.',
    'sign-document.sig.hint.picture': 'The paper is made transparent and the strokes take the ink colour.',
    'sign-document.sig.typeLabel': 'Your name',
    'sign-document.sig.pickPicture': 'Choose a picture',
    'sign-document.sig.pictureHint': 'A photo or scan of your signature in dark ink on plain light paper works best.',
    'sign-document.sig.save': 'Save signature',
    'sign-document.sig.clear': 'Clear',
    'sign-document.sig.cancel': 'Cancel',
    'sign-document.sig.emptyPad': 'The signature is empty.',
    'sign-document.sig.saved': 'Signature saved in this browser',
    'sign-document.sig.notStored': 'Signature ready. It couldn’t be stored in this browser, so it’s gone when you close the page.',
    'sign-document.sig.place': 'Place signature {n}',
    'sign-document.sig.remove': 'Remove signature {n}',
    'sign-document.sig.removeTitle': 'remove signature',
    'sign-document.sig.removeBody': 'The signature is removed from this browser. Documents you already saved keep it.',
    'sign-document.sig.removeOk': 'Remove',
    'sign-document.sig.removed': 'Signature removed',

    'sign-document.discard.title': 'discard changes',
    'sign-document.discard.body': 'What you added to this document hasn’t been saved and will be lost.',
    'sign-document.discard.ok': 'Discard',
    'sign-document.empty.title': 'nothing added yet',
    'sign-document.empty.body': 'You haven’t added a signature, drawing or text. Save an unchanged copy anyway?',
    'sign-document.empty.ok': 'Save anyway',

    'sign-document.error.title': 'couldn’t do that',
    'sign-document.error.type': 'Choose a PDF, PNG, JPEG or WebP file.',
    'sign-document.error.pdf': 'This file couldn’t be read as a PDF. It may be damaged.',
    'sign-document.error.encrypted': 'This PDF is encrypted or password protected, so it can’t be changed here.',
    'sign-document.error.unsupported': 'This browser is missing a feature needed to show PDFs here. A recent version of any major browser works.',
    'sign-document.error.image': 'This picture couldn’t be opened.',
    'sign-document.error.save': 'The signed copy couldn’t be made. Your document is unchanged.',
  },
};
