// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

export const strings = {
  en: {
    'todo-list.name': 'todo list',
    'todo-list.lists': 'Lists',
    'todo-list.defaultList': 'Tasks',
    'todo-list.listPattern': 'List {n}',
    'todo-list.newList': 'New list',
    'todo-list.listName': 'List name',
    'todo-list.deleteList': 'Delete list',
    'todo-list.openCount': '{n} open',
    'todo-list.add': 'Add',
    'todo-list.addPlaceholder': 'Add a task',
    'todo-list.addLabel': 'New task',
    'todo-list.empty': 'Nothing to do. Add a task above.',
    'todo-list.allDone': 'All done.',
    'todo-list.openTasks': 'Open tasks',
    'todo-list.doneSection': 'Done ({n})',
    'todo-list.clearDone': 'Clear done',
    'todo-list.reorder': 'Reorder: {task}',
    'todo-list.reorderHint': 'Drag, or use the up and down arrow keys.',
    'todo-list.important': 'Important',
    'todo-list.importantFor': 'Important: {task}',
    'todo-list.details': 'Details',
    'todo-list.task': 'Task',
    'todo-list.due': 'Due date',
    'todo-list.clearDue': 'Remove date',
    'todo-list.note': 'Note',
    'todo-list.steps': 'Steps',
    'todo-list.addStep': 'Add a step',
    'todo-list.removeStep': 'Remove step: {step}',
    'todo-list.stepCount': '{done}/{total} steps',
    'todo-list.hasNote': 'note',
    'todo-list.deleteTask': 'Delete task',
    'todo-list.close': 'Close',
    'todo-list.options': 'Options',
    'todo-list.overdue': 'Overdue, {date}',
    'todo-list.today': 'Today',
    'todo-list.tomorrow': 'Tomorrow',
    'todo-list.undo': 'Undo',
    'todo-list.undone': 'Restored',
    'todo-list.deletedTask': 'Task deleted',
    'todo-list.deletedList': 'List deleted',
    'todo-list.clearedDone': 'Done tasks cleared',
    'todo-list.added': 'Added: {task}',
    'todo-list.markedDone': 'Done: {task}',
    'todo-list.markedOpen': 'Open again: {task}',
    'todo-list.moved': 'Position {pos} of {n}',
    'todo-list.full': 'Storage is full. The latest change was not saved.',
  },
};
