// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

export const strings = {
  en: {
    'work-rest-timer.name': 'work and rest timer',
    'work-rest-timer.pageTitle': '{time} {phase} · sloppify',

    'work-rest-timer.phase.work': 'work',
    'work-rest-timer.phase.short': 'short rest',
    'work-rest-timer.phase.long': 'long rest',
    'work-rest-timer.round': 'round {n} of {total}',
    'work-rest-timer.today': 'work sessions today: {n}',
    'work-rest-timer.timer': 'Time left',

    'work-rest-timer.start': 'Start',
    'work-rest-timer.startPhase': 'Start {phase}',
    'work-rest-timer.pause': 'Pause',
    'work-rest-timer.resume': 'Resume',
    'work-rest-timer.reset': 'Reset',
    'work-rest-timer.skip': 'Skip',
    'work-rest-timer.minimal': 'Minimal',
    'work-rest-timer.options': 'Settings',
    'work-rest-timer.minimalOn': 'Minimal view. Press Escape to leave.',
    'work-rest-timer.exitMinimal': 'Leave minimal view',
    'work-rest-timer.hourglass': 'Hourglass, {pct} percent of this {phase} passed',

    'work-rest-timer.ended.work': 'Work done. Time for a {next}.',
    'work-rest-timer.ended.short': 'Rest over. Back to work.',
    'work-rest-timer.ended.long': 'Long rest over. A new cycle starts.',
    'work-rest-timer.started': '{phase} started, {time}',
    'work-rest-timer.paused': 'Paused at {time}',
    'work-rest-timer.skipped': 'Skipped to {phase}',
    'work-rest-timer.wasReset': '{phase} reset',

    'work-rest-timer.intervals': 'Intervals',
    'work-rest-timer.preset': 'Preset',
    'work-rest-timer.preset.classic': '25 / 5',
    'work-rest-timer.preset.long': '50 / 10',
    'work-rest-timer.preset.deep': '90 / 20',
    'work-rest-timer.preset.custom': 'custom',
    'work-rest-timer.preset.classicLabel': '25 minutes work, 5 minutes rest',
    'work-rest-timer.preset.longLabel': '50 minutes work, 10 minutes rest',
    'work-rest-timer.preset.deepLabel': '90 minutes work, 20 minutes rest',
    'work-rest-timer.preset.customLabel': 'Custom intervals',
    'work-rest-timer.field.work': 'Work',
    'work-rest-timer.field.short': 'Short rest',
    'work-rest-timer.field.long': 'Long rest',
    'work-rest-timer.field.rounds': 'Rounds before a long rest',
    'work-rest-timer.min': 'min',
    'work-rest-timer.autoStart': 'Start the next phase by itself',

    'work-rest-timer.sound': 'Sound',
    'work-rest-timer.workSound': 'When work ends',
    'work-rest-timer.restSound': 'When a rest ends',
    'work-rest-timer.sound.chime': 'chime',
    'work-rest-timer.sound.bowl': 'singing bowl',
    'work-rest-timer.sound.rise': 'rising notes',
    'work-rest-timer.sound.beeps': 'beeps (louder)',
    'work-rest-timer.sound.alarm': 'alarm (louder)',
    'work-rest-timer.sound.none': 'no sound',
    'work-rest-timer.volume': 'Volume',
    'work-rest-timer.test': 'Play',
    'work-rest-timer.testLabel': 'Play the sound for {when}',
    'work-rest-timer.when.work': 'when work ends',
    'work-rest-timer.when.rest': 'when a rest ends',

    'work-rest-timer.alerts': 'Alerts',
    'work-rest-timer.glow': 'Soft glow on the screen',
    'work-rest-timer.glowHint': 'A slow fade of colour, two seconds per pulse. Nothing flashes.',
    'work-rest-timer.notify': 'Notification when the page is in the background',
    'work-rest-timer.notifyDenied': 'Notifications are blocked for this site in your browser settings.',
    'work-rest-timer.notifyUnsupported': 'This browser doesn’t support notifications here.',
    'work-rest-timer.vibrate': 'Vibrate (phones)',
    'work-rest-timer.notifyTitle': '{phase} done',
    'work-rest-timer.testAlerts': 'Try the alerts',

    'work-rest-timer.keys': 'Keys: Space starts or pauses, R resets, S skips, M switches the minimal view.',
  },
};
