// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

export const strings = {
  en: {
    'stream-overlay.name': 'stream overlay',
    'stream-overlay.intro': 'Mark where your camera, chat and other sources go. The zones stay invisible: they only bend the generated art around them, so the screen looks layered and three dimensional.',

    'stream-overlay.stage': 'Overlay preview, {w} × {h}',
    'stream-overlay.stageHelp': 'Drag a zone to move it, or its corner to resize it. With the keyboard, arrow keys move the selected zone and Shift with arrow keys resizes it.',
    'stream-overlay.showZones': 'Show zones',
    'stream-overlay.drawing': 'Drawing',
    'stream-overlay.error': 'The preview couldn’t be drawn in this browser.',

    'stream-overlay.zones': 'zones',
    'stream-overlay.zone': 'selected zone',
    'stream-overlay.zone.label': '{name}: left {x}, top {y}, {w} by {h}',
    'stream-overlay.zone.none': 'No zones yet. Add one to shape the art.',
    'stream-overlay.zone.max': 'That’s the most zones a layout can have.',
    'stream-overlay.zone.add': 'Add zone',
    'stream-overlay.zone.addKind': 'Kind of zone to add',
    'stream-overlay.zone.remove': 'Remove zone',
    'stream-overlay.say.added': '{name} added',
    'stream-overlay.say.removed': '{name} removed',

    'stream-overlay.kind': 'Kind',
    'stream-overlay.kind.camera': 'camera',
    'stream-overlay.kind.chat': 'chat',
    'stream-overlay.kind.game': 'game',
    'stream-overlay.kind.alerts': 'alerts',
    'stream-overlay.kind.info': 'info panel',
    'stream-overlay.kind.buttons': 'buttons',
    'stream-overlay.kind.other': 'other',
    'stream-overlay.kind.canvas': 'canvas',

    'stream-overlay.effect': 'Effect on the art',
    'stream-overlay.effect.lift': 'raised',
    'stream-overlay.effect.sink': 'sunken',
    'stream-overlay.effect.orbit': 'orbit',
    'stream-overlay.effect.splash': 'paint splash',
    'stream-overlay.effect.pile': 'gravity',
    'stream-overlay.effect.none': 'plain window',
    'stream-overlay.effect.tape': 'tape',
    'stream-overlay.effect.brush': 'brush strokes',
    'stream-overlay.effect.sketch': 'sketch',
    'stream-overlay.effect.watercolor': 'watercolour',
    'stream-overlay.effect.vines': 'vines',
    'stream-overlay.effect.glitch': 'glitch',
    'stream-overlay.hint.lift': 'The zone floats above the art, which bends up and around it and takes its shadow.',
    'stream-overlay.hint.sink': 'The zone is a pit: the art spirals and slopes down into it.',
    'stream-overlay.hint.orbit': 'The art swirls around the zone, with rings passing behind it.',
    'stream-overlay.hint.splash': 'Paint splats around the edges and drips down.',
    'stream-overlay.hint.pile': 'Pieces fall onto the top edge, pile up and slide off the sides.',
    'stream-overlay.hint.none': 'The art just clears out of the zone.',
    'stream-overlay.hint.tape': 'Strips of see-through tape hold the zone’s corners, as if it’s taped to the wall. Strength adds more corners.',
    'stream-overlay.hint.brush': 'Dry brush strokes sweep around the edges and break into bristle streaks as they run out of paint.',
    'stream-overlay.hint.sketch': 'Pencil construction lines run past the corners, with hatched shading on the shadow side.',
    'stream-overlay.hint.watercolor': 'Watercolour washes bleed out from the edges, darker where the pigment pools.',
    'stream-overlay.hint.vines': 'Vines grow out from the edges, droop, branch and put out leaves.',
    'stream-overlay.hint.glitch': 'Colour slices tear off the sides and the outline slips out of register.',

    'stream-overlay.place': 'Content sits',
    'stream-overlay.place.over': 'on top of the art',
    'stream-overlay.place.under': 'under the art’s edges',

    'stream-overlay.x': 'Left',
    'stream-overlay.y': 'Top',
    'stream-overlay.w': 'Width',
    'stream-overlay.h': 'Height',
    'stream-overlay.r': 'Corner radius',
    'stream-overlay.frame': 'Frame',
    'stream-overlay.fuzz': 'Edge roughness',
    'stream-overlay.power': 'Strength',

    'stream-overlay.art': 'art',
    'stream-overlay.style': 'Style',
    'stream-overlay.style.sheet': 'draped lines',
    'stream-overlay.style.flow': 'flow lines',
    'stream-overlay.style.contour': 'contours',
    'stream-overlay.style.dots': 'halftone dots',
    'stream-overlay.style.hatch': 'pen hatching',
    'stream-overlay.style.none': 'zone effects only',
    'stream-overlay.palette': 'Colours',
    'stream-overlay.palette.ember': 'ember',
    'stream-overlay.palette.neon': 'neon',
    'stream-overlay.palette.moss': 'moss',
    'stream-overlay.palette.ocean': 'ocean',
    'stream-overlay.palette.paper': 'paper',
    'stream-overlay.palette.mono': 'mono',
    'stream-overlay.palette.kraft': 'kraft paper',
    'stream-overlay.palette.pastel': 'pastel',
    'stream-overlay.density': 'Detail',
    'stream-overlay.reach': 'Reach from the zones',
    'stream-overlay.reach.all': 'whole screen',
    'stream-overlay.percent': '{n}%',
    'stream-overlay.px': '{n} px',
    'stream-overlay.fill': 'Fill the background',
    'stream-overlay.seed': 'New pattern',

    'stream-overlay.layout': 'layout',
    'stream-overlay.size': 'Canvas size',
    'stream-overlay.size.wide': '{w} × {h}',
    'stream-overlay.size.tall': '{w} × {h}, vertical',
    'stream-overlay.preset': 'Starting layout',
    'stream-overlay.preset.gameplay': 'gameplay',
    'stream-overlay.preset.chatting': 'just chatting',
    'stream-overlay.preset.intermission': 'break screen',
    'stream-overlay.preset.art': 'art stream',
    'stream-overlay.preset.use': 'Use layout',
    'stream-overlay.preset.title': 'replace this layout?',
    'stream-overlay.preset.body': 'Your zones and art settings will be replaced by the {name} layout.',
    'stream-overlay.preset.ok': 'Replace',

    'stream-overlay.use': 'use it',
    'stream-overlay.layer.back': 'back',
    'stream-overlay.layer.front': 'front',
    'stream-overlay.download.back': 'Download back layer',
    'stream-overlay.download.front': 'Download front layer',
    'stream-overlay.link.back': 'Back layer link',
    'stream-overlay.link.front': 'Front layer link',
    'stream-overlay.copy': 'Copy',
    'stream-overlay.copy.back': 'Copy back layer link',
    'stream-overlay.copy.front': 'Copy front layer link',
    'stream-overlay.copied': 'Link copied',
    'stream-overlay.copyManual': 'Copying isn’t allowed here. The link is selected, so copy it yourself.',
    'stream-overlay.preparing': 'Drawing the full size image',
    'stream-overlay.frontEmpty': 'No zone has its content under the art, so the front layer is empty and you can leave it out.',
    'stream-overlay.step.back': 'In your streaming software, add the back layer at the bottom of the scene, as an image or as a browser source sized {w} × {h}.',
    'stream-overlay.step.content': 'Add your camera, game, chat and other sources above it, each placed in its zone.',
    'stream-overlay.step.front': 'Add the front layer above everything else.',
    'stream-overlay.step.link': 'A link holds the whole design and draws it when the browser source loads. After changing the design, copy the links again.',

    'stream-overlay.view.label': '{layer} layer of the overlay, {w} × {h}',
    'stream-overlay.view.invalid': 'This link doesn’t hold a valid overlay. Copy it again from the stream overlay tool.',
  },
};
