// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

export const strings = {
  en: {
    'random.name': 'random',
    'random.modes': 'Mode',
    'random.mode.wheel': 'wheel',
    'random.mode.dice': 'dice',
    'random.mode.numbers': 'numbers',
    'random.mode.straws': 'straws',
    'random.mode.coin': 'coin',
    'random.mode.shuffle': 'shuffle',
    'random.mode.teams': 'teams',

    'random.entries': 'Entries, one per line',
    'random.entriesCount': '{n} entries',
    'random.needTwo': 'Add at least two entries.',
    'random.listDefault.wheel': 'Pizza\nTacos\nSushi\nCurry\nSalad\nBurgers',
    'random.listDefault.people': 'Alex\nSam\nJo\nRobin',

    'random.wheel.spin': 'Spin',
    'random.wheel.label': 'Wheel with {n} entries',
    'random.wheel.remove': 'Remove the winner after each spin',
    'random.wheel.result': 'The wheel landed on {item}',

    'random.dice.add': 'Add a d{sides}',
    'random.dice.remove': 'Remove a d{sides}',
    'random.dice.pool': 'Dice to roll',
    'random.dice.notation': 'Dice notation',
    'random.dice.notationHint': 'For example 2d6 + 3, or d20 + d4 − 1',
    'random.dice.invalid': 'Write dice like 2d6 + 3: up to 30 dice with 2 to 1000 sides.',
    'random.dice.modifier': 'Modifier',
    'random.dice.modDown': 'Lower the modifier',
    'random.dice.modUp': 'Raise the modifier',
    'random.dice.d20': 'd20 rolls',
    'random.dice.none': 'normal',
    'random.dice.adv': 'advantage',
    'random.dice.dis': 'disadvantage',
    'random.dice.roll': 'Roll',
    'random.dice.clear': 'Clear',
    'random.dice.empty': 'Add dice to roll.',
    'random.dice.die': 'd{sides}: {value}',
    'random.dice.dropped': 'd{sides}: {value}, dropped',
    'random.dice.total': 'Total',
    'random.dice.nat20': 'natural 20',
    'random.dice.nat1': 'natural 1',
    'random.dice.result': '{dice}: {total}',

    'random.numbers.min': 'From',
    'random.numbers.max': 'To',
    'random.numbers.count': 'How many',
    'random.numbers.unique': 'No repeats',
    'random.numbers.sort': 'Sort',
    'random.numbers.pick': 'Pick',
    'random.numbers.error.range': 'Use whole numbers between −1,000,000,000 and 1,000,000,000.',
    'random.numbers.error.count': 'Pick between 1 and 100 numbers.',
    'random.numbers.error.unique': 'There aren’t that many different numbers in the range.',
    'random.numbers.result': '{min} to {max}: {values}',

    'random.straws.draw': 'New straws',
    'random.straws.pullAll': 'Pull all',
    'random.straws.pull': 'Pull the straw for {name}',
    'random.straws.pulled': '{name}: straw {len} of {n}',
    'random.straws.hint': 'Everyone pulls a straw. The shortest one loses.',
    'random.straws.left': '{n} straws left',
    'random.straws.result': '{name} drew the shortest straw',
    'random.straws.short': 'shortest',

    'random.coin.flip': 'Flip',
    'random.coin.heads': 'heads',
    'random.coin.tails': 'tails',
    'random.coin.tally': 'Heads {heads} · tails {tails}',
    'random.coin.reset': 'Reset count',
    'random.coin.result': '{side}',

    'random.shuffle.go': 'Shuffle',
    'random.shuffle.result': 'Order: {list}',

    'random.teams.count': 'Teams',
    'random.teams.go': 'Make teams',
    'random.teams.team': 'team {n}',
    'random.teams.tooFew': 'Add at least as many entries as teams.',
    'random.teams.result': '{teams}',

    'random.history': 'history',
    'random.history.empty': 'Results show up here.',
    'random.history.clear': 'Clear history',
    'random.fair': 'Every result uses your browser’s cryptographic random number generator, so all outcomes are equally likely. Nothing is sent anywhere.',
  },
};
