// SPDX-FileCopyrightText: 2026 sloppify contributors
// SPDX-License-Identifier: MIT

export const strings = {
  en: {
    'solitaire.name': 'solitaire',
    'solitaire.moves': 'moves',
    'solitaire.time': 'time',
    'solitaire.new': 'New game',
    'solitaire.undo': 'Undo',
    'solitaire.hint': 'Hint',
    'solitaire.options': 'Options',
    'solitaire.table': 'Card table',

    'solitaire.draw': 'Turn over',
    'solitaire.draw.1': 'one card',
    'solitaire.draw.3': 'three cards',
    'solitaire.draw.detail.1': 'easier',
    'solitaire.draw.detail.3': 'harder',

    'solitaire.rank.1': 'ace',
    'solitaire.rank.11': 'jack',
    'solitaire.rank.12': 'queen',
    'solitaire.rank.13': 'king',
    'solitaire.rank.short.1': 'A',
    'solitaire.rank.short.11': 'J',
    'solitaire.rank.short.12': 'Q',
    'solitaire.rank.short.13': 'K',
    'solitaire.suit.spades': 'spades',
    'solitaire.suit.hearts': 'hearts',
    'solitaire.suit.diamonds': 'diamonds',
    'solitaire.suit.clubs': 'clubs',
    'solitaire.card': '{rank} of {suit}',

    'solitaire.cards.0': 'empty',
    'solitaire.cards.1': '1 card',
    'solitaire.cards.n': '{n} cards',
    'solitaire.pile.stock': 'Stock, {cards}',
    'solitaire.pile.waste': 'Waste, {cards}',
    'solitaire.pile.foundation': 'Foundation {k}, {cards}',
    'solitaire.pile.column': 'Column {k}, {down} face down, {up} face up',
    'solitaire.slot.draw': 'Turn over cards, {n} left',
    'solitaire.slot.recycle': 'Turn the waste back over',
    'solitaire.slot.none': 'Stock and waste are empty',
    'solitaire.slot.empty': 'empty',
    'solitaire.pileName.waste': 'the waste',
    'solitaire.pileName.foundation': 'foundation {k}',
    'solitaire.pileName.column': 'column {k}',

    'solitaire.say.drawn': 'Turned over {card}',
    'solitaire.say.recycled': 'Waste turned back over into the stock',
    'solitaire.say.moved': '{card} to {pile}',
    'solitaire.say.movedRun': '{card} and {n} more to {pile}',
    'solitaire.say.flipped': 'Turned up {card}',
    'solitaire.say.picked': 'Picked up {card}. Move to a pile and press Enter, or Escape to cancel.',
    'solitaire.say.pickedRun': 'Picked up {card} and {n} more. Move to a pile and press Enter, or Escape to cancel.',
    'solitaire.say.cancel': 'Put back',
    'solitaire.say.noMove': 'No move for {card}',
    'solitaire.say.cantPlace': '{card} can’t go on {pile}',
    'solitaire.say.undone': 'Move undone',
    'solitaire.say.thinking': 'Looking for a move…',
    'solitaire.say.noHint': 'No winning line found from here. Try undoing a few moves.',
    'solitaire.say.hintDraw': 'Hint: turn over cards from the stock.',
    'solitaire.say.hintRecycle': 'Hint: turn the waste back over.',
    'solitaire.say.hintMove': 'Hint: {card} to {pile}.',
    'solitaire.say.hintRun': 'Hint: {card} and {n} more to {pile}.',
    'solitaire.say.finishing': 'Every card is face up. Finishing.',

    'solitaire.status.dealing': 'Shuffling…',
    'solitaire.status.won': 'Solved in {time} with {moves} moves.',
    'solitaire.status.best': 'Solved in {time} with {moves} moves. New best.',

    'solitaire.confirm.title': 'start a new game?',
    'solitaire.confirm.body': 'The game in progress will be lost.',
    'solitaire.confirm.ok': 'New game',

    'solitaire.stats': 'your record',
    'solitaire.stats.won': '{won} won of {played}',
    'solitaire.stats.best': 'best {time}, {moves} moves',
    'solitaire.stats.none': 'no games yet',

    'solitaire.help.title': 'how to play',
    'solitaire.help.goal': 'Move every card to the four foundations at the top, one suit on each, from ace to king. Every deal has been played through to a win by a solver first, so every game can be won.',
    'solitaire.help.columns': 'In the seven columns, build down in alternating colours: a red 6 on a black 7. A run that follows this can move together. Only a king, or a run starting with a king, can fill an empty column.',
    'solitaire.help.stock': 'When you’re stuck, turn over cards from the stock. When it runs out, turn the waste back over and go through it again.',
    'solitaire.help.hint': 'Stuck? Hint shows the next move of a winning line from where you are.',
    'solitaire.help.touch': 'Tap a card to send it to the best place, or drag it where you want it.',
    'solitaire.help.keys': 'Keyboard: arrow keys to move between cards, Enter to pick a card up and Enter again to put it down (twice on the same card sends it to the best place), Escape to cancel, U to undo, H for a hint.',
  },
};
